#' Convert a dataframe to a bedtools object
#' @param df A bedtools object that points to a file, and should have been generated by the bedtools command
#' @return  A bedtools object
#' @export
from_data_frame <- function(df){
    stopifnot(is.data.frame(df))
    location <- tmp_loc()
    suppressMessages(suppressWarnings(write_tsv(df, location, col_names = F)))
    return(bedtools_obj(location))
}
