#' Convert bedtools object to dataframe
#' @param obj A bedtools object that points to a file, and should have been generated by the bedtools command
#' @return  A data.frame
#' @export
to_data_frame <- function(obj){
    if(!is.bt_obj(obj)) stop('Can only convert an object to a data frame')
    location <- unclass(obj)
    df <-  suppressMessages(suppressWarnings(read_tsv(location, col_names = F)))
    return(df)
}
